<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>unla.tp</groupId> <!-- El groupId de tu pom padre -->
        <artifactId>tp-distribuidos-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>servicio-reservas</artifactId>

    <dependencies>
        <!-- Dependencia a tu repositorio de contratos gRPC -->
        <!-- Dependencias específicas de este servicio -->
    </dependencies>

    <build>
        <extensions>
            <!-- Detecta tu sistema operativo para descargar el compilador gRPC correcto -->
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.7.1</version>
            </extension>
        </extensions>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.xolstice.maven.plugins</groupId>
                <artifactId>protobuf-maven-plugin</artifactId>
                <version>0.6.1</version>
                <configuration>
                    <protocArtifact>com.google.protobuf:protoc:3.24.0:exe:${os.detected.classifier}</protocArtifact>
                    <pluginId>grpc-java</pluginId>
                    <pluginArtifact>io.grpc:protoc-gen-grpc-java:1.58.0:exe:${os.detected.classifier}</pluginArtifact>

                    <!-- 1. Ruta donde están tus archivos .proto -->
                    <protoSourceRoot>${project.parent.basedir}/proto/reservas</protoSourceRoot>

                    <!-- 2. Directorio destino unificado para los DTOs y Servicios gRPC -->
                    <outputDirectory>${project.basedir}/src/main/java/grpc</outputDirectory>

                    <!-- 3. CRÍTICO: Falso para evitar que el plugin elimine el resto de tus clases Java -->
                    <clearOutputDirectory>false</clearOutputDirectory>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compile-custom</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>