spring:
  config:
    import: optional:file:.env[.properties]
    
  application:
    name: tp_distribuidos

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  graphql:
    graphiql:
      enabled: true
logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: ${SERVER_PORT:8080}