// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface ClienteDniRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.ClienteDniRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dni = 1;</code>
   * @return The dni.
   */
  java.lang.String getDni();
  /**
   * <code>string dni = 1;</code>
   * @return The bytes for dni.
   */
  com.google.protobuf.ByteString
      getDniBytes();
}
