// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public final class ClientesProto {
  private ClientesProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ClienteDTO_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ClienteDTO_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_Metadatos_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_Metadatos_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ClienteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ClienteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_MetadatosRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_MetadatosRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ClienteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ClienteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ModificarClienteIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ModificarClienteIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ClienteIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ClienteIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ClienteDniRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ClienteDniRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ListarClientesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ListarClientesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clientes_ListarClientesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clientes_ListarClientesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016clientes.proto\022\010clientes\"\273\001\n\nClienteDT" +
      "O\022\n\n\002id\030\001 \001(\003\022\013\n\003dni\030\002 \001(\t\022\016\n\006nombre\030\003 \001" +
      "(\t\022\020\n\010apellido\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\022\020\n\010t" +
      "elefono\030\006 \001(\t\022\027\n\017fechaNacimiento\030\007 \001(\t\022\022" +
      "\n\nestaActivo\030\010 \001(\010\022$\n\007metados\030\t \001(\0132\023.cl" +
      "ientes.Metadatos\"G\n\tMetadatos\022\n\n\002id\030\001 \001(" +
      "\003\022\017\n\007usuario\030\002 \001(\t\022\020\n\010password\030\003 \001(\t\022\013\n\003" +
      "rol\030\004 \001(\t\"\250\001\n\016ClienteRequest\022\013\n\003dni\030\001 \001(" +
      "\t\022\016\n\006nombre\030\002 \001(\t\022\020\n\010apellido\030\003 \001(\t\022\r\n\005e" +
      "mail\030\004 \001(\t\022\020\n\010telefono\030\005 \001(\t\022\027\n\017fechaNac" +
      "imiento\030\006 \001(\t\022-\n\tmetadatos\030\007 \001(\0132\032.clien" +
      "tes.MetadatosRequest\"5\n\020MetadatosRequest" +
      "\022\017\n\007usuario\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"c\n\017C" +
      "lienteResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007messag" +
      "e\030\002 \001(\t\022\'\n\007cliente\030\003 \001(\0132\024.clientes.Clie" +
      "nteDTOH\000B\006\n\004data\"\277\001\n\031ModificarClienteIdR" +
      "equest\022\n\n\002id\030\001 \001(\003\022\013\n\003dni\030\002 \001(\t\022\016\n\006nombr" +
      "e\030\003 \001(\t\022\020\n\010apellido\030\004 \001(\t\022\r\n\005email\030\005 \001(\t" +
      "\022\020\n\010telefono\030\006 \001(\t\022\027\n\017fechaNacimiento\030\007 " +
      "\001(\t\022-\n\tmetadatos\030\010 \001(\0132\032.clientes.Metada" +
      "tosRequest\"\036\n\020ClienteIdRequest\022\n\n\002id\030\001 \001" +
      "(\003\" \n\021ClienteDniRequest\022\013\n\003dni\030\001 \001(\t\"\027\n\025" +
      "ListarClientesRequest\"`\n\026ListarClientesR" +
      "esponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t" +
      "\022%\n\007cliente\030\003 \003(\0132\024.clientes.ClienteDTO2" +
      "\376\004\n\016clienteService\022C\n\014CrearCliente\022\030.cli" +
      "entes.ClienteRequest\032\031.clientes.ClienteR" +
      "esponse\022T\n\022ModificarClienteId\022#.clientes" +
      ".ModificarClienteIdRequest\032\031.clientes.Cl" +
      "ienteResponse\022J\n\023ModificarClienteDni\022\030.c" +
      "lientes.ClienteRequest\032\031.clientes.Client" +
      "eResponse\022K\n\022ConsultarClienteId\022\032.client" +
      "es.ClienteIdRequest\032\031.clientes.ClienteRe" +
      "sponse\022M\n\023ConsultarClienteDni\022\033.clientes" +
      ".ClienteDniRequest\032\031.clientes.ClienteRes" +
      "ponse\022S\n\016ListarClientes\022\037.clientes.Lista" +
      "rClientesRequest\032 .clientes.ListarClient" +
      "esResponse\022H\n\017BorrarClienteId\022\032.clientes" +
      ".ClienteIdRequest\032\031.clientes.ClienteResp" +
      "onse\022J\n\020BorrarClienteDni\022\033.clientes.Clie" +
      "nteDniRequest\032\031.clientes.ClienteResponse" +
      "B\027\n\004grpcB\rClientesProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_clientes_ClienteDTO_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clientes_ClienteDTO_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ClienteDTO_descriptor,
        new java.lang.String[] { "Id", "Dni", "Nombre", "Apellido", "Email", "Telefono", "FechaNacimiento", "EstaActivo", "Metados", });
    internal_static_clientes_Metadatos_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_clientes_Metadatos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_Metadatos_descriptor,
        new java.lang.String[] { "Id", "Usuario", "Password", "Rol", });
    internal_static_clientes_ClienteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_clientes_ClienteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ClienteRequest_descriptor,
        new java.lang.String[] { "Dni", "Nombre", "Apellido", "Email", "Telefono", "FechaNacimiento", "Metadatos", });
    internal_static_clientes_MetadatosRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_clientes_MetadatosRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_MetadatosRequest_descriptor,
        new java.lang.String[] { "Usuario", "Password", });
    internal_static_clientes_ClienteResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_clientes_ClienteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ClienteResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Cliente", "Data", });
    internal_static_clientes_ModificarClienteIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_clientes_ModificarClienteIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ModificarClienteIdRequest_descriptor,
        new java.lang.String[] { "Id", "Dni", "Nombre", "Apellido", "Email", "Telefono", "FechaNacimiento", "Metadatos", });
    internal_static_clientes_ClienteIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_clientes_ClienteIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ClienteIdRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_clientes_ClienteDniRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_clientes_ClienteDniRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ClienteDniRequest_descriptor,
        new java.lang.String[] { "Dni", });
    internal_static_clientes_ListarClientesRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_clientes_ListarClientesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ListarClientesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_clientes_ListarClientesResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_clientes_ListarClientesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clientes_ListarClientesResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Cliente", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
