// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

/**
 * Protobuf type {@code clientes.ClienteRequest}
 */
public final class ClienteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clientes.ClienteRequest)
    ClienteRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClienteRequest.newBuilder() to construct.
  private ClienteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClienteRequest() {
    dni_ = "";
    nombre_ = "";
    apellido_ = "";
    email_ = "";
    telefono_ = "";
    fechaNacimiento_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClienteRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ClientesProto.internal_static_clientes_ClienteRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ClientesProto.internal_static_clientes_ClienteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ClienteRequest.class, grpc.ClienteRequest.Builder.class);
  }

  private int bitField0_;
  public static final int DNI_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dni_ = "";
  /**
   * <code>string dni = 1;</code>
   * @return The dni.
   */
  @java.lang.Override
  public java.lang.String getDni() {
    java.lang.Object ref = dni_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dni_ = s;
      return s;
    }
  }
  /**
   * <code>string dni = 1;</code>
   * @return The bytes for dni.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDniBytes() {
    java.lang.Object ref = dni_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dni_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NOMBRE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nombre_ = "";
  /**
   * <code>string nombre = 2;</code>
   * @return The nombre.
   */
  @java.lang.Override
  public java.lang.String getNombre() {
    java.lang.Object ref = nombre_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nombre_ = s;
      return s;
    }
  }
  /**
   * <code>string nombre = 2;</code>
   * @return The bytes for nombre.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNombreBytes() {
    java.lang.Object ref = nombre_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nombre_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APELLIDO_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object apellido_ = "";
  /**
   * <code>string apellido = 3;</code>
   * @return The apellido.
   */
  @java.lang.Override
  public java.lang.String getApellido() {
    java.lang.Object ref = apellido_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      apellido_ = s;
      return s;
    }
  }
  /**
   * <code>string apellido = 3;</code>
   * @return The bytes for apellido.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getApellidoBytes() {
    java.lang.Object ref = apellido_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      apellido_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>string email = 4;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>string email = 4;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TELEFONO_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object telefono_ = "";
  /**
   * <code>string telefono = 5;</code>
   * @return The telefono.
   */
  @java.lang.Override
  public java.lang.String getTelefono() {
    java.lang.Object ref = telefono_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      telefono_ = s;
      return s;
    }
  }
  /**
   * <code>string telefono = 5;</code>
   * @return The bytes for telefono.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTelefonoBytes() {
    java.lang.Object ref = telefono_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      telefono_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FECHANACIMIENTO_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object fechaNacimiento_ = "";
  /**
   * <code>string fechaNacimiento = 6;</code>
   * @return The fechaNacimiento.
   */
  @java.lang.Override
  public java.lang.String getFechaNacimiento() {
    java.lang.Object ref = fechaNacimiento_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fechaNacimiento_ = s;
      return s;
    }
  }
  /**
   * <code>string fechaNacimiento = 6;</code>
   * @return The bytes for fechaNacimiento.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFechaNacimientoBytes() {
    java.lang.Object ref = fechaNacimiento_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fechaNacimiento_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATOS_FIELD_NUMBER = 7;
  private grpc.MetadatosRequest metadatos_;
  /**
   * <code>.clientes.MetadatosRequest metadatos = 7;</code>
   * @return Whether the metadatos field is set.
   */
  @java.lang.Override
  public boolean hasMetadatos() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.clientes.MetadatosRequest metadatos = 7;</code>
   * @return The metadatos.
   */
  @java.lang.Override
  public grpc.MetadatosRequest getMetadatos() {
    return metadatos_ == null ? grpc.MetadatosRequest.getDefaultInstance() : metadatos_;
  }
  /**
   * <code>.clientes.MetadatosRequest metadatos = 7;</code>
   */
  @java.lang.Override
  public grpc.MetadatosRequestOrBuilder getMetadatosOrBuilder() {
    return metadatos_ == null ? grpc.MetadatosRequest.getDefaultInstance() : metadatos_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dni_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dni_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nombre_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nombre_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(apellido_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, apellido_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telefono_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, telefono_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fechaNacimiento_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fechaNacimiento_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(7, getMetadatos());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dni_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dni_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nombre_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nombre_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(apellido_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, apellido_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(telefono_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, telefono_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(fechaNacimiento_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fechaNacimiento_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getMetadatos());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ClienteRequest)) {
      return super.equals(obj);
    }
    grpc.ClienteRequest other = (grpc.ClienteRequest) obj;

    if (!getDni()
        .equals(other.getDni())) return false;
    if (!getNombre()
        .equals(other.getNombre())) return false;
    if (!getApellido()
        .equals(other.getApellido())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getTelefono()
        .equals(other.getTelefono())) return false;
    if (!getFechaNacimiento()
        .equals(other.getFechaNacimiento())) return false;
    if (hasMetadatos() != other.hasMetadatos()) return false;
    if (hasMetadatos()) {
      if (!getMetadatos()
          .equals(other.getMetadatos())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DNI_FIELD_NUMBER;
    hash = (53 * hash) + getDni().hashCode();
    hash = (37 * hash) + NOMBRE_FIELD_NUMBER;
    hash = (53 * hash) + getNombre().hashCode();
    hash = (37 * hash) + APELLIDO_FIELD_NUMBER;
    hash = (53 * hash) + getApellido().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + TELEFONO_FIELD_NUMBER;
    hash = (53 * hash) + getTelefono().hashCode();
    hash = (37 * hash) + FECHANACIMIENTO_FIELD_NUMBER;
    hash = (53 * hash) + getFechaNacimiento().hashCode();
    if (hasMetadatos()) {
      hash = (37 * hash) + METADATOS_FIELD_NUMBER;
      hash = (53 * hash) + getMetadatos().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ClienteRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ClienteRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ClienteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ClienteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ClienteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ClienteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ClienteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ClienteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.ClienteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.ClienteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ClienteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ClienteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ClienteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clientes.ClienteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clientes.ClienteRequest)
      grpc.ClienteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ClientesProto.internal_static_clientes_ClienteRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ClientesProto.internal_static_clientes_ClienteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ClienteRequest.class, grpc.ClienteRequest.Builder.class);
    }

    // Construct using grpc.ClienteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadatosFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dni_ = "";
      nombre_ = "";
      apellido_ = "";
      email_ = "";
      telefono_ = "";
      fechaNacimiento_ = "";
      metadatos_ = null;
      if (metadatosBuilder_ != null) {
        metadatosBuilder_.dispose();
        metadatosBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ClientesProto.internal_static_clientes_ClienteRequest_descriptor;
    }

    @java.lang.Override
    public grpc.ClienteRequest getDefaultInstanceForType() {
      return grpc.ClienteRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ClienteRequest build() {
      grpc.ClienteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ClienteRequest buildPartial() {
      grpc.ClienteRequest result = new grpc.ClienteRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.ClienteRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dni_ = dni_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.nombre_ = nombre_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.apellido_ = apellido_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.email_ = email_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.telefono_ = telefono_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.fechaNacimiento_ = fechaNacimiento_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.metadatos_ = metadatosBuilder_ == null
            ? metadatos_
            : metadatosBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ClienteRequest) {
        return mergeFrom((grpc.ClienteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ClienteRequest other) {
      if (other == grpc.ClienteRequest.getDefaultInstance()) return this;
      if (!other.getDni().isEmpty()) {
        dni_ = other.dni_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNombre().isEmpty()) {
        nombre_ = other.nombre_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getApellido().isEmpty()) {
        apellido_ = other.apellido_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTelefono().isEmpty()) {
        telefono_ = other.telefono_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getFechaNacimiento().isEmpty()) {
        fechaNacimiento_ = other.fechaNacimiento_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.hasMetadatos()) {
        mergeMetadatos(other.getMetadatos());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dni_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              nombre_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              apellido_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              email_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              telefono_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              fechaNacimiento_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getMetadatosFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object dni_ = "";
    /**
     * <code>string dni = 1;</code>
     * @return The dni.
     */
    public java.lang.String getDni() {
      java.lang.Object ref = dni_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dni_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dni = 1;</code>
     * @return The bytes for dni.
     */
    public com.google.protobuf.ByteString
        getDniBytes() {
      java.lang.Object ref = dni_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dni_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dni = 1;</code>
     * @param value The dni to set.
     * @return This builder for chaining.
     */
    public Builder setDni(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dni_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string dni = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDni() {
      dni_ = getDefaultInstance().getDni();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string dni = 1;</code>
     * @param value The bytes for dni to set.
     * @return This builder for chaining.
     */
    public Builder setDniBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dni_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object nombre_ = "";
    /**
     * <code>string nombre = 2;</code>
     * @return The nombre.
     */
    public java.lang.String getNombre() {
      java.lang.Object ref = nombre_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nombre_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nombre = 2;</code>
     * @return The bytes for nombre.
     */
    public com.google.protobuf.ByteString
        getNombreBytes() {
      java.lang.Object ref = nombre_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nombre_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nombre = 2;</code>
     * @param value The nombre to set.
     * @return This builder for chaining.
     */
    public Builder setNombre(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nombre_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string nombre = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNombre() {
      nombre_ = getDefaultInstance().getNombre();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string nombre = 2;</code>
     * @param value The bytes for nombre to set.
     * @return This builder for chaining.
     */
    public Builder setNombreBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nombre_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object apellido_ = "";
    /**
     * <code>string apellido = 3;</code>
     * @return The apellido.
     */
    public java.lang.String getApellido() {
      java.lang.Object ref = apellido_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        apellido_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string apellido = 3;</code>
     * @return The bytes for apellido.
     */
    public com.google.protobuf.ByteString
        getApellidoBytes() {
      java.lang.Object ref = apellido_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        apellido_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string apellido = 3;</code>
     * @param value The apellido to set.
     * @return This builder for chaining.
     */
    public Builder setApellido(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      apellido_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string apellido = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearApellido() {
      apellido_ = getDefaultInstance().getApellido();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string apellido = 3;</code>
     * @param value The bytes for apellido to set.
     * @return This builder for chaining.
     */
    public Builder setApellidoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      apellido_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string email = 4;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string email = 4;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object telefono_ = "";
    /**
     * <code>string telefono = 5;</code>
     * @return The telefono.
     */
    public java.lang.String getTelefono() {
      java.lang.Object ref = telefono_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        telefono_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string telefono = 5;</code>
     * @return The bytes for telefono.
     */
    public com.google.protobuf.ByteString
        getTelefonoBytes() {
      java.lang.Object ref = telefono_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        telefono_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string telefono = 5;</code>
     * @param value The telefono to set.
     * @return This builder for chaining.
     */
    public Builder setTelefono(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      telefono_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string telefono = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTelefono() {
      telefono_ = getDefaultInstance().getTelefono();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string telefono = 5;</code>
     * @param value The bytes for telefono to set.
     * @return This builder for chaining.
     */
    public Builder setTelefonoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      telefono_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object fechaNacimiento_ = "";
    /**
     * <code>string fechaNacimiento = 6;</code>
     * @return The fechaNacimiento.
     */
    public java.lang.String getFechaNacimiento() {
      java.lang.Object ref = fechaNacimiento_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fechaNacimiento_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fechaNacimiento = 6;</code>
     * @return The bytes for fechaNacimiento.
     */
    public com.google.protobuf.ByteString
        getFechaNacimientoBytes() {
      java.lang.Object ref = fechaNacimiento_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fechaNacimiento_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fechaNacimiento = 6;</code>
     * @param value The fechaNacimiento to set.
     * @return This builder for chaining.
     */
    public Builder setFechaNacimiento(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      fechaNacimiento_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string fechaNacimiento = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFechaNacimiento() {
      fechaNacimiento_ = getDefaultInstance().getFechaNacimiento();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string fechaNacimiento = 6;</code>
     * @param value The bytes for fechaNacimiento to set.
     * @return This builder for chaining.
     */
    public Builder setFechaNacimientoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      fechaNacimiento_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private grpc.MetadatosRequest metadatos_;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.MetadatosRequest, grpc.MetadatosRequest.Builder, grpc.MetadatosRequestOrBuilder> metadatosBuilder_;
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     * @return Whether the metadatos field is set.
     */
    public boolean hasMetadatos() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     * @return The metadatos.
     */
    public grpc.MetadatosRequest getMetadatos() {
      if (metadatosBuilder_ == null) {
        return metadatos_ == null ? grpc.MetadatosRequest.getDefaultInstance() : metadatos_;
      } else {
        return metadatosBuilder_.getMessage();
      }
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    public Builder setMetadatos(grpc.MetadatosRequest value) {
      if (metadatosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadatos_ = value;
      } else {
        metadatosBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    public Builder setMetadatos(
        grpc.MetadatosRequest.Builder builderForValue) {
      if (metadatosBuilder_ == null) {
        metadatos_ = builderForValue.build();
      } else {
        metadatosBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    public Builder mergeMetadatos(grpc.MetadatosRequest value) {
      if (metadatosBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          metadatos_ != null &&
          metadatos_ != grpc.MetadatosRequest.getDefaultInstance()) {
          getMetadatosBuilder().mergeFrom(value);
        } else {
          metadatos_ = value;
        }
      } else {
        metadatosBuilder_.mergeFrom(value);
      }
      if (metadatos_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    public Builder clearMetadatos() {
      bitField0_ = (bitField0_ & ~0x00000040);
      metadatos_ = null;
      if (metadatosBuilder_ != null) {
        metadatosBuilder_.dispose();
        metadatosBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    public grpc.MetadatosRequest.Builder getMetadatosBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getMetadatosFieldBuilder().getBuilder();
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    public grpc.MetadatosRequestOrBuilder getMetadatosOrBuilder() {
      if (metadatosBuilder_ != null) {
        return metadatosBuilder_.getMessageOrBuilder();
      } else {
        return metadatos_ == null ?
            grpc.MetadatosRequest.getDefaultInstance() : metadatos_;
      }
    }
    /**
     * <code>.clientes.MetadatosRequest metadatos = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.MetadatosRequest, grpc.MetadatosRequest.Builder, grpc.MetadatosRequestOrBuilder> 
        getMetadatosFieldBuilder() {
      if (metadatosBuilder_ == null) {
        metadatosBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.MetadatosRequest, grpc.MetadatosRequest.Builder, grpc.MetadatosRequestOrBuilder>(
                getMetadatos(),
                getParentForChildren(),
                isClean());
        metadatos_ = null;
      }
      return metadatosBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clientes.ClienteRequest)
  }

  // @@protoc_insertion_point(class_scope:clientes.ClienteRequest)
  private static final grpc.ClienteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ClienteRequest();
  }

  public static grpc.ClienteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClienteRequest>
      PARSER = new com.google.protobuf.AbstractParser<ClienteRequest>() {
    @java.lang.Override
    public ClienteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClienteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClienteRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ClienteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

