// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface ClienteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.ClienteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.clientes.ClienteDTO cliente = 3;</code>
   * @return Whether the cliente field is set.
   */
  boolean hasCliente();
  /**
   * <code>.clientes.ClienteDTO cliente = 3;</code>
   * @return The cliente.
   */
  grpc.ClienteDTO getCliente();
  /**
   * <code>.clientes.ClienteDTO cliente = 3;</code>
   */
  grpc.ClienteDTOOrBuilder getClienteOrBuilder();

  grpc.ClienteResponse.DataCase getDataCase();
}
