// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface ListarClientesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.ListarClientesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  java.util.List<grpc.ClienteDTO> 
      getClienteList();
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  grpc.ClienteDTO getCliente(int index);
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  int getClienteCount();
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  java.util.List<? extends grpc.ClienteDTOOrBuilder> 
      getClienteOrBuilderList();
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  grpc.ClienteDTOOrBuilder getClienteOrBuilder(
      int index);
}
