// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

/**
 * Protobuf type {@code clientes.ListarClientesResponse}
 */
public final class ListarClientesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:clientes.ListarClientesResponse)
    ListarClientesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListarClientesResponse.newBuilder() to construct.
  private ListarClientesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListarClientesResponse() {
    status_ = "";
    message_ = "";
    cliente_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListarClientesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ClientesProto.internal_static_clientes_ListarClientesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ClientesProto.internal_static_clientes_ListarClientesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ListarClientesResponse.class, grpc.ListarClientesResponse.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";
  /**
   * <code>string status = 1;</code>
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 1;</code>
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object message_ = "";
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<grpc.ClienteDTO> cliente_;
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  @java.lang.Override
  public java.util.List<grpc.ClienteDTO> getClienteList() {
    return cliente_;
  }
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends grpc.ClienteDTOOrBuilder> 
      getClienteOrBuilderList() {
    return cliente_;
  }
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  @java.lang.Override
  public int getClienteCount() {
    return cliente_.size();
  }
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  @java.lang.Override
  public grpc.ClienteDTO getCliente(int index) {
    return cliente_.get(index);
  }
  /**
   * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
   */
  @java.lang.Override
  public grpc.ClienteDTOOrBuilder getClienteOrBuilder(
      int index) {
    return cliente_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    for (int i = 0; i < cliente_.size(); i++) {
      output.writeMessage(3, cliente_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    for (int i = 0; i < cliente_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, cliente_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ListarClientesResponse)) {
      return super.equals(obj);
    }
    grpc.ListarClientesResponse other = (grpc.ListarClientesResponse) obj;

    if (!getStatus()
        .equals(other.getStatus())) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (!getClienteList()
        .equals(other.getClienteList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (getClienteCount() > 0) {
      hash = (37 * hash) + CLIENTE_FIELD_NUMBER;
      hash = (53 * hash) + getClienteList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ListarClientesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ListarClientesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ListarClientesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ListarClientesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ListarClientesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ListarClientesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ListarClientesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ListarClientesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.ListarClientesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.ListarClientesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ListarClientesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ListarClientesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ListarClientesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code clientes.ListarClientesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:clientes.ListarClientesResponse)
      grpc.ListarClientesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ClientesProto.internal_static_clientes_ListarClientesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ClientesProto.internal_static_clientes_ListarClientesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ListarClientesResponse.class, grpc.ListarClientesResponse.Builder.class);
    }

    // Construct using grpc.ListarClientesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      status_ = "";
      message_ = "";
      if (clienteBuilder_ == null) {
        cliente_ = java.util.Collections.emptyList();
      } else {
        cliente_ = null;
        clienteBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ClientesProto.internal_static_clientes_ListarClientesResponse_descriptor;
    }

    @java.lang.Override
    public grpc.ListarClientesResponse getDefaultInstanceForType() {
      return grpc.ListarClientesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ListarClientesResponse build() {
      grpc.ListarClientesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ListarClientesResponse buildPartial() {
      grpc.ListarClientesResponse result = new grpc.ListarClientesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(grpc.ListarClientesResponse result) {
      if (clienteBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          cliente_ = java.util.Collections.unmodifiableList(cliente_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.cliente_ = cliente_;
      } else {
        result.cliente_ = clienteBuilder_.build();
      }
    }

    private void buildPartial0(grpc.ListarClientesResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.message_ = message_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ListarClientesResponse) {
        return mergeFrom((grpc.ListarClientesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ListarClientesResponse other) {
      if (other == grpc.ListarClientesResponse.getDefaultInstance()) return this;
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (clienteBuilder_ == null) {
        if (!other.cliente_.isEmpty()) {
          if (cliente_.isEmpty()) {
            cliente_ = other.cliente_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureClienteIsMutable();
            cliente_.addAll(other.cliente_);
          }
          onChanged();
        }
      } else {
        if (!other.cliente_.isEmpty()) {
          if (clienteBuilder_.isEmpty()) {
            clienteBuilder_.dispose();
            clienteBuilder_ = null;
            cliente_ = other.cliente_;
            bitField0_ = (bitField0_ & ~0x00000004);
            clienteBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getClienteFieldBuilder() : null;
          } else {
            clienteBuilder_.addAllMessages(other.cliente_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              message_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              grpc.ClienteDTO m =
                  input.readMessage(
                      grpc.ClienteDTO.parser(),
                      extensionRegistry);
              if (clienteBuilder_ == null) {
                ensureClienteIsMutable();
                cliente_.add(m);
              } else {
                clienteBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 1;</code>
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 1;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string status = 1;</code>
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      message_ = getDefaultInstance().getMessage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      message_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<grpc.ClienteDTO> cliente_ =
      java.util.Collections.emptyList();
    private void ensureClienteIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        cliente_ = new java.util.ArrayList<grpc.ClienteDTO>(cliente_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.ClienteDTO, grpc.ClienteDTO.Builder, grpc.ClienteDTOOrBuilder> clienteBuilder_;

    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public java.util.List<grpc.ClienteDTO> getClienteList() {
      if (clienteBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cliente_);
      } else {
        return clienteBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public int getClienteCount() {
      if (clienteBuilder_ == null) {
        return cliente_.size();
      } else {
        return clienteBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public grpc.ClienteDTO getCliente(int index) {
      if (clienteBuilder_ == null) {
        return cliente_.get(index);
      } else {
        return clienteBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder setCliente(
        int index, grpc.ClienteDTO value) {
      if (clienteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClienteIsMutable();
        cliente_.set(index, value);
        onChanged();
      } else {
        clienteBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder setCliente(
        int index, grpc.ClienteDTO.Builder builderForValue) {
      if (clienteBuilder_ == null) {
        ensureClienteIsMutable();
        cliente_.set(index, builderForValue.build());
        onChanged();
      } else {
        clienteBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder addCliente(grpc.ClienteDTO value) {
      if (clienteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClienteIsMutable();
        cliente_.add(value);
        onChanged();
      } else {
        clienteBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder addCliente(
        int index, grpc.ClienteDTO value) {
      if (clienteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClienteIsMutable();
        cliente_.add(index, value);
        onChanged();
      } else {
        clienteBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder addCliente(
        grpc.ClienteDTO.Builder builderForValue) {
      if (clienteBuilder_ == null) {
        ensureClienteIsMutable();
        cliente_.add(builderForValue.build());
        onChanged();
      } else {
        clienteBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder addCliente(
        int index, grpc.ClienteDTO.Builder builderForValue) {
      if (clienteBuilder_ == null) {
        ensureClienteIsMutable();
        cliente_.add(index, builderForValue.build());
        onChanged();
      } else {
        clienteBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder addAllCliente(
        java.lang.Iterable<? extends grpc.ClienteDTO> values) {
      if (clienteBuilder_ == null) {
        ensureClienteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cliente_);
        onChanged();
      } else {
        clienteBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder clearCliente() {
      if (clienteBuilder_ == null) {
        cliente_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        clienteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public Builder removeCliente(int index) {
      if (clienteBuilder_ == null) {
        ensureClienteIsMutable();
        cliente_.remove(index);
        onChanged();
      } else {
        clienteBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public grpc.ClienteDTO.Builder getClienteBuilder(
        int index) {
      return getClienteFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public grpc.ClienteDTOOrBuilder getClienteOrBuilder(
        int index) {
      if (clienteBuilder_ == null) {
        return cliente_.get(index);  } else {
        return clienteBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public java.util.List<? extends grpc.ClienteDTOOrBuilder> 
         getClienteOrBuilderList() {
      if (clienteBuilder_ != null) {
        return clienteBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cliente_);
      }
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public grpc.ClienteDTO.Builder addClienteBuilder() {
      return getClienteFieldBuilder().addBuilder(
          grpc.ClienteDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public grpc.ClienteDTO.Builder addClienteBuilder(
        int index) {
      return getClienteFieldBuilder().addBuilder(
          index, grpc.ClienteDTO.getDefaultInstance());
    }
    /**
     * <code>repeated .clientes.ClienteDTO cliente = 3;</code>
     */
    public java.util.List<grpc.ClienteDTO.Builder> 
         getClienteBuilderList() {
      return getClienteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.ClienteDTO, grpc.ClienteDTO.Builder, grpc.ClienteDTOOrBuilder> 
        getClienteFieldBuilder() {
      if (clienteBuilder_ == null) {
        clienteBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.ClienteDTO, grpc.ClienteDTO.Builder, grpc.ClienteDTOOrBuilder>(
                cliente_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        cliente_ = null;
      }
      return clienteBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:clientes.ListarClientesResponse)
  }

  // @@protoc_insertion_point(class_scope:clientes.ListarClientesResponse)
  private static final grpc.ListarClientesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ListarClientesResponse();
  }

  public static grpc.ListarClientesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListarClientesResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListarClientesResponse>() {
    @java.lang.Override
    public ListarClientesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListarClientesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListarClientesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ListarClientesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

