// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface ListarClientesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.ListarClientesRequest)
    com.google.protobuf.MessageOrBuilder {
}
