// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface MetadatosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.MetadatosRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string usuario = 1;</code>
   * @return The usuario.
   */
  java.lang.String getUsuario();
  /**
   * <code>string usuario = 1;</code>
   * @return The bytes for usuario.
   */
  com.google.protobuf.ByteString
      getUsuarioBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
