// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface MetadatosOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.Metadatos)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string usuario = 2;</code>
   * @return The usuario.
   */
  java.lang.String getUsuario();
  /**
   * <code>string usuario = 2;</code>
   * @return The bytes for usuario.
   */
  com.google.protobuf.ByteString
      getUsuarioBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string rol = 4;</code>
   * @return The rol.
   */
  java.lang.String getRol();
  /**
   * <code>string rol = 4;</code>
   * @return The bytes for rol.
   */
  com.google.protobuf.ByteString
      getRolBytes();
}
