// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: clientes.proto

package grpc;

public interface ModificarClienteIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clientes.ModificarClienteIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string dni = 2;</code>
   * @return The dni.
   */
  java.lang.String getDni();
  /**
   * <code>string dni = 2;</code>
   * @return The bytes for dni.
   */
  com.google.protobuf.ByteString
      getDniBytes();

  /**
   * <code>string nombre = 3;</code>
   * @return The nombre.
   */
  java.lang.String getNombre();
  /**
   * <code>string nombre = 3;</code>
   * @return The bytes for nombre.
   */
  com.google.protobuf.ByteString
      getNombreBytes();

  /**
   * <code>string apellido = 4;</code>
   * @return The apellido.
   */
  java.lang.String getApellido();
  /**
   * <code>string apellido = 4;</code>
   * @return The bytes for apellido.
   */
  com.google.protobuf.ByteString
      getApellidoBytes();

  /**
   * <code>string email = 5;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 5;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string telefono = 6;</code>
   * @return The telefono.
   */
  java.lang.String getTelefono();
  /**
   * <code>string telefono = 6;</code>
   * @return The bytes for telefono.
   */
  com.google.protobuf.ByteString
      getTelefonoBytes();

  /**
   * <code>string fechaNacimiento = 7;</code>
   * @return The fechaNacimiento.
   */
  java.lang.String getFechaNacimiento();
  /**
   * <code>string fechaNacimiento = 7;</code>
   * @return The bytes for fechaNacimiento.
   */
  com.google.protobuf.ByteString
      getFechaNacimientoBytes();

  /**
   * <code>.clientes.MetadatosRequest metadatos = 8;</code>
   * @return Whether the metadatos field is set.
   */
  boolean hasMetadatos();
  /**
   * <code>.clientes.MetadatosRequest metadatos = 8;</code>
   * @return The metadatos.
   */
  grpc.MetadatosRequest getMetadatos();
  /**
   * <code>.clientes.MetadatosRequest metadatos = 8;</code>
   */
  grpc.MetadatosRequestOrBuilder getMetadatosOrBuilder();
}
